### ISSUE TITLE
New update cause crash

### ISSUE THREAD

**Issue by lily148** [prasad-edlabadka/homebridge-tuya-ir#4]
Hi, the new update seem like crash... with the following error.

```
/usr/local/lib/node_modules/homebridge-tuya-ir/src/lib/TuyaAPIHelper.ts:180
            cb(body, error);
            ^
TypeError: Cannot read property 'length' of undefined
    at /usr/local/lib/node_modules/homebridge-tuya-ir/src/lib/TuyaAPIHelper.ts:61:33
    at Request._callback (/usr/local/lib/node_modules/homebridge-tuya-ir/src/lib/TuyaAPIHelper.ts:180:13)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-tuya-ir/node_modules/request/request.js:185:22)
    at Request.emit (events.js:375:28)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-tuya-ir/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:375:28)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-tuya-ir/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:481:28)
    at IncomingMessage.emit (events.js:387:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
```

**Comment by lily148** [comment]
I published an pull request to fix this crash...

**Comment by prasad-edlabadka** [comment]
#5 Pull request merged
