### ISSUE TITLE
Cannot find API Service "Device Connection Service"

### ISSUE THREAD

**Issue by TadeSF** [prasad-edlabadka/homebridge-tuya-ir#40]
Is it possible that Tuya changed the name of the "Device Connection Service" again? No matter what I try, I can't find anything resembling this Service and apparently it is not working without.

**Comment by prasad-edlabadka** [comment]
Working fine for me. Can you please share logs?

**Comment by prasad-edlabadka** [comment]
Closing due to no response. Please free free to reopen

**Comment by ugabiga** [comment]
Here is my log
```
[6/25/2022, 1:23:24 AM] [TuyaIR] Failed to get remote configuration for: eb88a28b3d8407df7114zr
[6/25/2022, 1:23:24 AM] [TuyaIR] Server returned error: 'permission deny'
TypeError: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at new NodeError (node:internal/errors:372:5)
    at Hash.update (node:internal/crypto/hash:105:11)
    at Object.generate (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/uuid.ts:11:11)
    at /usr/local/lib/node_modules/homebridge-tuya-ir/src/platform.ts:91:42
    at /usr/local/lib/node_modules/homebridge-tuya-ir/src/lib/TuyaIRDiscovery.ts:25:17
    at /usr/local/lib/node_modules/homebridge-tuya-ir/src/lib/TuyaAPIHelper.ts:149:21
    at Request._callback (/usr/local/lib/node_modules/homebridge-tuya-ir/src/lib/TuyaAPIHelper.ts:406:13)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-tuya-ir/node_modules/request/request.js:185:22)
    at Request.emit (node:events:527:28)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-tuya-ir/node_modules/request/request.js:1154:10)
```
and I couldn't find "Device Connection Service". I attached my service search result.
<img width="1260" alt="Screen Shot 2022-06-25 at 1 26 45 AM" src="https://user-images.githubusercontent.com/10293433/175577607-c0810836-7aa7-46e6-98df-5e3274c6d8e4.png">

Thanks!
