### ISSUE TITLE
Sign Invalid

### ISSUE THREAD

**Issue by Rahulsharma0810** [prasad-edlabadka/homebridge-tuya-ir#51]
I am getting the below logs when trying to add AC IR remote, cross-checked client_id/secret all are correct.

```
[6/7/2022, 5:22:43 PM] [homebridge-tuya-ir] This plugin generated a warning from the characteristic 'Manufacturer': characteristic value expected string and received undefined. See https://homebridge.io/w/JtMGR for more info.
[6/7/2022, 5:22:43 PM] [TuyaIR] Failed to get AC status due to error sign invalid
[6/7/2022, 5:22:43 PM] Error: HAP Status Error: -70402
    at new HapStatusError (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/hapStatusError.ts:15:5)
    at /usr/local/lib/node_modules/homebridge-tuya-ir/src/lib/accessories/AirConditionerAccessory.ts:96:23
    at /usr/local/lib/node_modules/homebridge-tuya-ir/src/lib/TuyaAPIHelper.ts:215:13
    at Request._callback (/usr/local/lib/node_modules/homebridge-tuya-ir/src/lib/TuyaAPIHelper.ts:406:13)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-tuya-ir/node_modules/request/request.js:185:22)
    at Request.emit (node:events:527:28)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-tuya-ir/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:527:28)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-tuya-ir/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:641:28)
[6/7/2022, 5:22:43 PM] Got SIGTERM, shutting down Homebridge...
```

**Comment by prasad-edlabadka** [comment]
Which version of the plugin are you using? Are you using correct region? I haven't seen this error for a while now.

**Comment by prasad-edlabadka** [comment]
Closing due to non-activity. Please feel free to re-open with logs.
