### ISSUE TITLE
Errors after updating 1.0.7/1.0.8

### ISSUE THREAD

**Issue by zixuan96** [prasad-edlabadka/homebridge-tuya-ir#78]
Those errors appeared after updating 1.0.7/1.0.8.

`TypeError: Cannot read properties of undefined (reading 'values')
    at /usr/lib/node_modules/homebridge-tuya-ir/src/lib/accessories/AirConditionerAccessory.ts:78:106
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-tuya-ir/src/lib/api/APIInvocationHelper.ts:54:21)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)`

**Comment by prasad-edlabadka** [comment]
Fixed in v1.0.9. Please update and let me know.

**Comment by zixuan96** [comment]
This problem is solved.
